import "./css/base.css";
import Menu from "../componentes/menu.js";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <header>
          FRETE GRATIS PARS TODO BRASIL!!
        </header>
        <nav>
          <Menu/>
        </nav>
        <main>
          {children}
        </main>
       
        
      </body>
    </html>
  )
}
